stages:
  - build
  - test
  - release

variables:
  PACKAGE_NAME: Cimpress.Cimbol

.tags: &tags-common
  tags:
    - docker
    - dotnetcore
    - linux

build:fea:
  <<: *tags-common
  image: mcr.microsoft.com/dotnet/core/sdk:2.1
  stage: build
  only:
    refs:
      - merge_requests
  script:
    - dotnet build -c Release -o $(pwd)/build

build:prd:
  <<: *tags-common
  image: mcr.microsoft.com/dotnet/core/sdk:2.1
  stage: build
  artifacts:
    paths:
      - build/Cimpress.Cimbol.dll
      - build/Cimpress.Cimbol.pdb
  only:
    refs:
      - master
  script:
    - dotnet build -c Release -o $(pwd)/build

benchmark:fea:
  <<: *tags-common
  image: mcr.microsoft.com/dotnet/core/sdk:2.1
  stage: test
  only:
    refs:
      - merge_requests
  script:
    - export PATH="$PATH:/root/.dotnet/tools"
    - dotnet tool install -g BenchmarkDotNet.Tool
    - dotnet build test/Cimpress.Cimbol.PerformanceTests/Cimpress.Cimbol.PerformanceTests.csproj -c Release -o $(pwd)/build
    - dotnet benchmark build/Cimpress.Cimbol.PerformanceTests.dll -f Cimpress.Cimbol.PerformanceTests*

test:fea:
  <<: *tags-common
  image: mcr.microsoft.com/dotnet/core/sdk:2.1
  stage: test
  only:
    refs:
      - merge_requests
  script:
    - dotnet test -c Release

benchmark:prd:
  <<: *tags-common
  image: mcr.microsoft.com/dotnet/core/sdk:2.1
  stage: test
  artifacts:
    paths:
      - artifacts/benchmark-report*
  only:
    refs:
      - master
  script:
    - export PATH="$PATH:/root/.dotnet/tools"
    - dotnet tool install -g BenchmarkDotNet.Tool
    - dotnet build test/Cimpress.Cimbol.PerformanceTests/Cimpress.Cimbol.PerformanceTests.csproj -c Release -o $(pwd)/build
    - mkdir artifacts
    - dotnet benchmark build/Cimpress.Cimbol.PerformanceTests.dll -f Cimpress.Cimbol.PerformanceTests* -a artifacts -e briefjson -j medium --join
    - cp ./artifacts/results/*.json artifacts/benchmark-report-$(date +%s).json

test:prd:
  <<: *tags-common
  image: mcr.microsoft.com/dotnet/core/sdk:2.1
  stage: test
  only:
    refs:
      - master
  script:
    - dotnet test -c Release

release:prd:
  <<: *tags-common
  image: mcr.microsoft.com/dotnet/core/sdk:2.1
  stage: release
  dependencies:
    - build:prd
  only:
    changes:
      - Cimpress.Cimbol.nuspec
    refs:
      - master
  script:
    - dotnet restore
    - dotnet pack --no-build -p:NuspecFile=$(pwd)/Cimpress.Cimbol.nuspec -o $(pwd)/build
    - dotnet nuget push build/*.nupkg -k $CT_ARTIFACTORY_USERNAME:$CT_ARTIFACTORY_API_KEY -s $CT_ARTIFACTORY_NUGET_URL
